[2022-10-23T18:19:42.387+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T18:19:39.302486+00:00 [queued]>
[2022-10-23T18:19:42.398+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T18:19:39.302486+00:00 [queued]>
[2022-10-23T18:19:42.398+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T18:19:42.399+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-23T18:19:42.400+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-23T18:19:42.416+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_vendas> on 2022-10-23 18:19:39.302486+00:00
[2022-10-23T18:19:42.420+0000] {standard_task_runner.py:54} INFO - Started process 7880 to run task
[2022-10-23T18:19:42.423+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sales_datawarehouse', 'get_vendas', 'manual__2022-10-23T18:19:39.302486+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/sales_dw.py', '--cfg-path', '/tmp/tmpdud1k7e5']
[2022-10-23T18:19:42.425+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask get_vendas
[2022-10-23T18:19:42.427+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/sales_dw.py
[2022-10-23T18:19:42.939+0000] {task_command.py:384} INFO - Running <TaskInstance: sales_datawarehouse.get_vendas manual__2022-10-23T18:19:39.302486+00:00 [running]> on host 499050b57294
[2022-10-23T18:19:43.020+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pedromenegat
AIRFLOW_CTX_DAG_ID=sales_datawarehouse
AIRFLOW_CTX_TASK_ID=get_vendas
AIRFLOW_CTX_EXECUTION_DATE=2022-10-23T18:19:39.302486+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-23T18:19:39.302486+00:00
[2022-10-23T18:19:43.141+0000] {base.py:71} INFO - Using connection ID 'banco_vendas' for task execution.
[2022-10-23T18:19:45.133+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-10-23T18:19:45.155+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=sales_datawarehouse, task_id=get_vendas, execution_date=20221023T181939, start_date=20221023T181942, end_date=20221023T181945
[2022-10-23T18:19:45.218+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-23T18:19:45.244+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
